
services:
  core:
    image: dms-api:dev
    depends_on:
      - db
      - search
      - redis
    environment:
      CORE_APP: /core_app
      PAPERMERGE__DATABASE__URL: postgresql://liquid:snake@db:5432/dms
      PAPERMERGE__REDIS__URL: redis://redis/0
      PAPERMERGE__OCR__DEFAULT_LANGUAGE: eng
      PAPERMERGE__MAIN__API_PREFIX: ""
      PAPERMERGE__SECURITY__SECRET_KEY: 183781
      PAPERMERGE__MAIN__MEDIA_ROOT: /data/DMS/media/
      PAPERMERGE__MAIN__TIMEZONE: Asia/Dhaka
      PAPERMERGE__SECURITY__TOKEN_EXPIRE_MINUTES: 30
      PAPERMERGE__SEARCH__URL: solr://search:8983/dms
      PAPERMERGE__DEVELOPER__LOGIN: yes
      
    volumes:
      - ./DMS/media:/data/DMS/media
      - ./DMS:/app/logs
    expose:
      - 80

  web:
    image: dms-web:dev
    expose:
      - 80

  ocr:
    image: dms-ocr:dev
    depends_on:
      - redis
      - db
    environment:
      PAPERMERGE__DATABASE__URL: postgresql://liquid:snake@db:5432/dms
      PAPERMERGE__REDIS__URL: redis://redis/0
      PAPERMERGE__MAIN__MEDIA_ROOT: /data/DMS/media/
    volumes:
      - ./DMS/media:/data/DMS/media
      - ./DMS:/app/logs

  search:
    image: solr:latest
    ports:
      - 8983:8983
    volumes:
      - ./DMS/solr:/var/solr
    command:
      - solr-precreate
      - dms

  index:
    image: dms-index:latest
    depends_on:
      - db
      - search
      - redis
    environment:
      PAPERMERGE__DATABASE__URL: postgresql://liquid:snake@db:5432/dms
      PAPERMERGE__REDIS__URL: redis://redis/0
      PAPERMERGE__SEARCH__URL: solr://search:8983/dms
    volumes:
      - ./DMS:/app/logs

  redis:
    image: redis:6
    healthcheck:
      test: redis-cli --raw incr ping
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  nginx:
    image: nginx:alpine
    ports:
      - 80:80 # Only NGINX is exposed externally
    depends_on:
      - core
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  db:
    image: postgres:16.1
    volumes:
      - dms-pgdata:/var/lib/postgresql/data/
    ports:
     - "3000:5432"
    environment:
      POSTGRES_PASSWORD: snake
      POSTGRES_DB: dms
      POSTGRES_USER: liquid
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
volumes:
  dms-pgdata: